version: '3.9'
services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - timescaledb
    environment:
      WAIT_HOSTS: kafka:9092, timescaledb:5432
      WAIT_BEFORE: 15
      POSTGRES_HOST: timescaledb
      KAFKA_URL: kafka:9092
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      BACKEND_HOST: backend
      WAIT_HOSTS: kafka:9092, timescaledb:5432, backend:8080
      WAIT_BEFORE: 25
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  kafka:
    image: confluentinc/cp-kafka:6.1.4
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  timescaledb:
    image: timescale/timescaledb:2.6.0-pg12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "timemaster"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "timeseries"
